<a href="https://colab.research.google.com/github/harshyadav42/Python-Numpy/blob/main/Complete_Numpylibrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np              #importing numpy library as np

In [2]:
np.__version__

'2.1.3'

In [3]:
list1=[1,2,3]                     #creating a list
array1=np.array([1,2,3])          #creating a array

In [4]:
type(list1)                        #checking type of list and array
type(array1)

numpy.ndarray

In [5]:
list_result=[x ** 2 for x in list1]           #doing iteration in list

In [6]:
list_result

[1, 4, 9]

In [7]:
array_result=array1 ** 2                    #doing iteration in array

In [8]:
array_result

array([1, 4, 9])

In [9]:
marks_1d=np.array([85,90,78])   #creating a 1-d array

In [10]:
marks_1d

array([85, 90, 78])

In [11]:
marks_1d.ndim      # to check the dimensions

1

In [12]:
marks_0d=np.array(85)

In [13]:
marks_0d.ndim

0

In [15]:
marks_2d=np.array([[85,90,78],[88,92,80]])

In [17]:
marks_2d.ndim

2

In [19]:
marks_3d=np.array([[[85,90],[78,88]],[[92,80],[70,60]]])

In [20]:
marks_3d.ndim

3

In [21]:
np.zeros(2)   #creating an array with element as zero

array([0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,2))   #creating an array with element as one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.arange(1,10)      #to give all elements between specified range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.linspace(0,100,3)     #to give specified space between elements

array([  0.,  50., 100.])

In [31]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [32]:
arr=np.array([1.5,2.7,3.1])

In [35]:
print(arr.dtype)     #to check the datatype of array

float64


In [37]:
a=np.array([[1,2,3],[4,5,6]])

In [38]:
print("shape:",a.shape)      #to check the shape

shape: (2, 3)


In [39]:
print("size:",a.size)          #to check the size

size: 6


In [40]:
arr = np.array([10, 20, 30, 40])

In [41]:
print(arr[0])     #accessing value using indexing

10


In [42]:
arr[2] = 99      #modifying elements of array

In [43]:
print(arr)

[10 20 99 40]


In [44]:
arr_2d = np.array([[5, 10], [15, 20]])  #2d array

In [45]:
arr_2d[0]

array([ 5, 10])

In [46]:
arr_2d[1,0]

np.int64(15)

In [47]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])       # 3D array

In [48]:
arr_3d[1, 0, 1]

np.int64(6)

In [49]:
# Slicing Arrays (arr[start:stop:step])
arr = np.array([10, 20, 30, 40, 50, 60])

In [50]:
print(arr[1:5])

[20 30 40 50]


In [51]:
print(arr[0:5:2])

[10 30 50]


In [52]:
print(arr[::2])

[10 30 50]


In [53]:
print(arr[::-1])

[60 50 40 30 20 10]


In [54]:
print(arr[::-2])

[60 40 20]


In [55]:
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [56]:
print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [57]:
# Boolean Indexing
scores = np.array([45, 78, 89, 90, 67])

In [58]:
scores > 80

array([False, False,  True,  True, False])

In [59]:
print(scores[scores > 80])

[89 90]


In [61]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]

In [62]:
print(arr[indices])

[10 30 50]


In [63]:
#Array Operations & Broadcasting

In [64]:
#Element-wise Arithmetic Operations
store1 = np.array([100, 150, 200])
store2 = np.array([90, 160, 210])

In [65]:
print("Add:", store1 + store2)
print("Subtract:", store1 - store2)
print("Multiply:", store1 * store2)
print("Divide:", store1 / store2)

Add: [190 310 410]
Subtract: [ 10 -10 -10]
Multiply: [ 9000 24000 42000]
Divide: [1.11111111 0.9375     0.95238095]


In [66]:
#Scalar Operations (Array + Number)
marks = np.array([60, 70, 80])

In [67]:
print(marks + 5)
print(marks * 2)

[65 75 85]
[120 140 160]


In [68]:
#Comparison Operations
scores = np.array([45, 67, 88, 39])

In [69]:
print(scores >= 50)

[False  True  True False]


In [70]:
#Logical Operations
scores = np.array([45, 67, 88, 39])

In [71]:
print((scores >= 50) & (scores > 70))
print((scores >= 50) | (scores > 70))
print(~(scores >= 50) | (scores > 70))

[False False  True False]
[False  True  True False]
[ True False  True  True]


In [72]:
#Aggregate Functions: sum(), min(), max(), mean()
marks = np.array([80, 90, 70, 60])

In [73]:
print("Total:", marks.sum())
print("Average:", marks.mean())
print("Min:", marks.min())
print("Max:", marks.max())

Total: 300
Average: 75.0
Min: 60
Max: 90


In [74]:
#Axis-based Aggregations
#Use axis=0 to aggregate column-wise, axis=1 for row-wise.
marks = np.array([[80, 90, 70],
[60, 85, 75]])

In [75]:
print(marks.sum(axis=0))
print(marks.sum(axis=1))

[140 175 145]
[240 220]


In [77]:
#Broadcasting in NumPy
#Broadcasting allows operations between arrays of different shapes (when compatible). NumPy "stretches" smaller arrays to match dimensions.

marks = np.array([[50, 60, 70],
[80, 90, 100]])
bonus = 10
# Broadcasting adds 10 to every element

In [78]:
print(marks + bonus)

[[ 60  70  80]
 [ 90 100 110]]


In [79]:
grades = np.array([[85, 90, 95],
[80, 85, 90]])
curve = np.array([1, 2, 3])

In [80]:
print(grades + curve)

[[86 92 98]
 [81 87 93]]


In [82]:
# Reshaping and Resizing Arrays
# Reshaping Arrays with .reshape()
arr=np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2, 3)


In [83]:
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
#Flattening an Array with .flatten()
matrix = np.array([[1, 2, 3],
[4, 5, 6]])
flat = matrix.flatten()

In [86]:
print(flat)

[1 2 3 4 5 6]


In [87]:
#Resizing Arrays with np.resize()
arr = np.array([1, 2, 3, 4])
resized = np.resize(arr, (2, 3))

In [88]:
print(resized)

[[1 2 3]
 [4 1 2]]


In [90]:
resized = np.resize(arr, (3, 3))
print(resized)

[[1 2 3]
 [4 1 2]
 [3 4 1]]


In [92]:
resized = np.resize(arr, (3, 2,3))
print(resized)

[[[1 2 3]
  [4 1 2]]

 [[3 4 1]
  [2 3 4]]

 [[1 2 3]
  [4 1 2]]]


In [94]:
resized = np.resize(arr, (7))
print(resized)

[1 2 3 4 1 2 3]


In [95]:
#Transpose Arrays with .T
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

In [96]:
print("Original:\n", matrix)
print("Transposed:\n", matrix.T)

Original:
 [[1 2]
 [3 4]
 [5 6]]
Transposed:
 [[1 3 5]
 [2 4 6]]


In [97]:
#Concatenating Arrays with np.concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
joined = np.concatenate((arr1, arr2))
print(joined)

[1 2 3 4 5 6]


In [99]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])
combined = np.concatenate((a, b), axis=0)
print(combined)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])
combined = np.concatenate((a, b), axis=1)
print(combined)

[[1 2 5 6]
 [3 4 7 8]]


In [101]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[10],[20]])
combined = np.concatenate((a, b), axis=1)
print(combined)

[[ 1  2 10]
 [ 3  4 20]]


In [103]:
#Using np.vstack() and np.hstack()
a = np.array([1, 2])
b = np.array([3, 4])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:\n", np.hstack((a, b)))

Vertical:
 [[1 2]
 [3 4]]
Horizontal:
 [1 2 3 4]


In [104]:
#Splitting Arrays with np.split()
#Breaks one array into multiple smaller arrays.
arr = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr, 3) # Split into 3 equal parts
print(split_arr)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [105]:
arr = np.array([10, 20, 30, 40, 50, 60,70,80,90])
split_arr = np.split(arr, 3) # Split into 3 equal parts
print(split_arr)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


In [107]:
#Splitting 2D Arrays
#Split 2D arrays by rows (vsplit) or columns (hsplit).
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8]])

In [108]:
# Split columns
left, right = np.hsplit(matrix, 2)
print("Left:\n", left)
print("Right:\n", right)

Left:
 [[1 2]
 [5 6]]
Right:
 [[3 4]
 [7 8]]


In [109]:
# Split rows
top, bottom = np.vsplit(matrix, 2)
print("Top:\n", top)
print("Bottom:\n", bottom)

Top:
 [[1 2 3 4]]
Bottom:
 [[5 6 7 8]]


In [113]:
# Copying and Views in NumPy
#A view is a new array that shares the same data with the original array.
#A copy is a completely separate array with its own data.

#Creating a View using Slicing
arr = np.array([10, 20, 30, 40])
view = arr[1:3]


In [114]:
view

array([20, 30])

In [115]:
view[0]=99

In [116]:
view

array([99, 30])

In [117]:
arr

array([10, 99, 30, 40])

In [4]:
#Creating a Copy using .copy()
arr = np.array([1, 2, 3, 4])
copy_arr = arr.copy()
copy_arr[0] = 99

In [5]:
print("Copy:", copy_arr) # [99 2 3 4]
print("Original:", arr) # [1 2 3 4] ← unchanged

Copy: [99  2  3  4]
Original: [1 2 3 4]


In [6]:
#Checking if Arrays Share Memory with np.may_share_memory()
from numpy import may_share_memory

arr = np.array([1, 2, 3, 4])
view = arr[1:]
copy = arr.copy()

print(may_share_memory(arr, view))
print(may_share_memory(arr, copy))

True
False


In [7]:
view

array([2, 3, 4])

In [9]:
#Iterating Over Arrays
#Using for Loops to Iterate Over 1D Arrays
fruits = np.array(['apple', 'banana', 'cherry'])
for fruit in fruits:
 print(fruit)

apple
banana
cherry


In [12]:
#Iterating Over 2D Arrays (Row by Row)
arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr:
 print("Row:", row)

Row: [1 2]
Row: [3 4]
Row: [5 6]


In [14]:
#Iterating Over Every Element Using flat
arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr.flat:
 print("Row:", row)

Row: 1
Row: 2
Row: 3
Row: 4
Row: 5
Row: 6


In [16]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr.flat:
 print("Row:", row,end=' ')

Row: 1 Row: 2 Row: 3 Row: 4 Row: 5 Row: 6 

In [18]:
arr = np.array([[1, 2], [3, 4]])
for val in arr.flat:
 print(val, end=' ')

1 2 3 4 

In [21]:
#Modifying Array Values with nditer()

arr = np.array([1, 2, 3])
for x in np.nditer(arr, op_flags=['readwrite']):
 x[...] = x * 2

 print("Modified:", arr)

Modified: [2 2 3]
Modified: [2 4 3]
Modified: [2 4 6]


In [24]:
#Iterating with Indexes Using ndenumerate()
# np.ndenumerate() gives both index and value, which is helpful in debugging
arr = np.array([100, 200])
for index, value in np.ndenumerate(arr):
 print(f"Index {index} has value {value}")

Index (0,) has value 100
Index (1,) has value 200


In [26]:
arr = np.array([[100, 200], [300, 400]])
for index, value in np.ndenumerate(arr):
 print(f"Index {index} has value {value}")

Index (0, 0) has value 100
Index (0, 1) has value 200
Index (1, 0) has value 300
Index (1, 1) has value 400


In [30]:
#Random Module in NumPy
# Introduction to numpy.random
# NumPy's random module helps you generate random numbers for simulations, testing, and sampling data.
# np.random.rand() # Random Floats (0 to 1)
# Generates random floats between 0 and 1. Useful when you want normalized data.
print(np.random.rand(3)) # 1D array

[0.17609549 0.97713752 0.86012289]


In [32]:
print(np.random.rand(2, 3)) # 2D array

[[0.48604404 0.16577361 0.04319877]
 [0.89080526 0.6074406  0.70609313]]


In [33]:
print(np.random.rand(2, 3,2)) # 3D array

[[[0.81705306 0.37402494]
  [0.98378513 0.74055949]
  [0.21706519 0.03758269]]

 [[0.53155673 0.71417846]
  [0.55530883 0.34268186]
  [0.29786092 0.62932843]]]


In [42]:
#Setting a Seed with np.random.seed()
#Use this to get repeatable results — important for debugging or reproducible experiments.
np.random.seed(42)
print(np.random.rand(2, 3,2))

[[[0.37454012 0.95071431]
  [0.73199394 0.59865848]
  [0.15601864 0.15599452]]

 [[0.05808361 0.86617615]
  [0.60111501 0.70807258]
  [0.02058449 0.96990985]]]


In [43]:
#np.random.randint() – Random Integers
#Generates random integers within a specified range.
print(np.random.randint(10, 20, size=5))

[15 11 14 10 19]


In [44]:
#np.random.randn() – Standard Normal Distribution
#Returns samples from the standard normal distribution (mean=0, std=1).
print(np.random.randn(4))

[-2.61254901  0.95036968  0.81644508 -1.523876  ]


In [45]:
print(np.random.randn(2, 3))

[[-0.42804606 -0.74240684 -0.7033438 ]
 [-2.13962066 -0.62947496  0.59772047]]


In [51]:
#np.random.choice() – Randomly Picking Elements
#Randomly selects items from a list or array.
items = ['apple', 'banana', 'cherry']
print(np.random.choice(items, size=2))

['apple' 'banana']


In [52]:
#np.random.shuffle() – Shuffle Elements In-place
#Randomly rearranges elements of the array in-place (modifies the original array).
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled:", arr)

Shuffled: [3 4 1 5 2]


In [53]:
arr

array([3, 4, 1, 5, 2])

In [54]:
#np.random.permutation() – Returns a Shuffled Copy
#Same as shuffle() but returns a new array, leaving the original unchanged.
arr = np.array([10, 20, 30, 40])
shuffled = np.random.permutation(arr)
print("Original:", arr)
print("Shuffled Copy:", shuffled)

Original: [10 20 30 40]
Shuffled Copy: [40 30 20 10]


In [55]:
#Mathematical Functions in NumPy
np.sum(arr)

np.int64(100)

In [57]:
np.mean(arr)

np.float64(25.0)

In [58]:
np.median(arr)

np.float64(25.0)

In [59]:
np.std(arr)

np.float64(11.180339887498949)

In [60]:
np.var(arr)

np.float64(125.0)

In [61]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [62]:
np.max(arr)

np.int64(40)

In [63]:
np.min(arr)

np.int64(10)

In [64]:
np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17])

In [66]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945])

In [67]:
#NumPy String Functions
names = np.array(['Alice', 'BOB', 'ChArLiE'])
print(np.char.lower(names))

['alice' 'bob' 'charlie']


In [68]:
print(np.char.upper(names))

['ALICE' 'BOB' 'CHARLIE']


In [69]:
print(np.char.upper(names[2]))

CHARLIE


In [70]:
arr = np.array(['hello', 'world'])
print(np.char.capitalize(arr))

['Hello' 'World']


In [71]:
first = np.array(['John', 'Jane'])
last = np.array(['Doe', 'Smith'])
print(np.char.add(first,last))

['JohnDoe' 'JaneSmith']


In [72]:
words = np.array(['Hi', 'Bye'])
print(np.char.multiply(words, 3))

['HiHiHi' 'ByeByeBye']


In [73]:
arr = np.array(['Hi', 'Hello'])
print(np.char.center(arr, 10, fillchar='*'))

['****Hi****' '**Hello***']


In [74]:
sentences = np.array(['Hello World', 'Python NumPy'])
print(np.char.split(sentences))

[list(['Hello', 'World']) list(['Python', 'NumPy'])]


In [75]:
arr = np.array([' apple ', ' banana'])
print(np.char.strip(arr))

['apple' 'banana']


In [77]:
arr = np.array(['I hate bugs', 'bugs are bad'])
print(np.char.replace(arr, 'bugs', 'features'))

['I hate features' 'features are bad']


In [78]:
emails = np.array(['user@example.com', 'admin@site.org'])
print(np.char.find(emails, '@'))

[4 5]


In [79]:
#NumPy DateTime Functions
#np.datetime64() – Creating Dates
#Creates a date or date-time object from a string.

date1 = np.datetime64('2025-05-08')
print(date1)

datetime1 = np.datetime64('2025-05-08T10:30')
print(datetime1)

2025-05-08
2025-05-08T10:30


In [80]:
#np.datetime64().astype(str) – Convert to String
#Convert datetime objects to strings (often for printing or exporting data).
dt = np.datetime64('2025-05-08')
print(dt.astype(str))

2025-05-08


In [82]:
dt = np.datetime64('2025-05-08')
strdate=dt.astype(str)

In [84]:
type(dt)

numpy.datetime64

In [85]:
type(strdate)

numpy.str_

In [92]:
#np.datetime64 with Units (D, M, Y, h, m, s)
print(np.datetime64('2025-05-08', 'Y'))
print(np.datetime64('2025-05', 'M'))
print(np.datetime64('2025-05-08T10:30', 'h'))

2025
2025-05
2025-05-08T10


In [93]:
#np.arange() with Date Ranges
#Create ranges of dates just like numbers.
dates = np.arange('2025-05-01', '2025-05-08', dtype='datetime64[D]')
print(dates)

['2025-05-01' '2025-05-02' '2025-05-03' '2025-05-04' '2025-05-05'
 '2025-05-06' '2025-05-07']


In [100]:
#np.timedelta64() – Date Difference / Duration
d1 = np.datetime64('2025-05-10')
d2 = np.datetime64('2025-04-01')
print("Difference:", d1 - d2)

Difference: 39 days


In [101]:
type(d1-d2)

numpy.timedelta64

In [102]:
#np.datetime64('today') – Get Current Date
print("Today:", np.datetime64('today'))

Today: 2026-09-27


In [103]:
#NumPy File I/O

#Key File I/O Functions in NumPy
data = np.array([[85, 90], [75, 80], [95, 92]])
np.savetxt("scores.csv", data, delimiter=",", fmt='%d')

In [104]:
loaded_scores = np.loadtxt("scores.csv", delimiter=",")
print(loaded_scores)

[[85. 90.]
 [75. 80.]
 [95. 92.]]


In [109]:
arr = np.array([1, 2, 3, 4])
np.save("my_array.npy", arr)

In [106]:
loaded_arr = np.load("my_array.npy")
print(loaded_arr)

[1 2 3 4]


In [111]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.savez("multiple_arrays.npz", array1=a, array2=b)

In [112]:
data = np.load("multiple_arrays.npz")
print(data['array1']) # [1 2 3]
print(data['array2']) # [4 5 6]

[1 2 3]
[4 5 6]


In [113]:
#NumPy and Linear Algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot() for matrix multiplication
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [114]:
A = np.array([[1, 2], [3, 4]])
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [117]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A * B
print(result)

[[ 5 12]
 [21 32]]


In [118]:
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
print("Determinant:", det)

Determinant: -2.0000000000000004


In [119]:
A = np.array([[1, 2], [3, 4]])
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [120]:
#To solve a system of linear equations Ax = b, you can use np.linalg.solve(A, b) to directly find x
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 18])
x = np.linalg.solve(A, b)
print("Solution:", x)

Solution: [1.2 5.6]


In [122]:
#Numpy Handling Missing Data
#Representing Missing Data with np.nan

# Array with NaN (missing) values
data = np.array([1, 2, np.nan, 4, 5, np.nan])
print(data)

[ 1.  2. nan  4.  5. nan]


In [123]:
#Checking for Missing Data (np.isnan())
# Check for NaN values
is_nan = np.isnan(data)
print("Check for NaN values:", is_nan)

Check for NaN values: [False False  True False False  True]


In [126]:
#Replacing Missing Values (np.nan_to_num())
# Replace NaN values with 0
cleaned_data = np.nan_to_num(data, nan=143)
print("Data After Replacing NaN with 0:", cleaned_data)

Data After Replacing NaN with 0: [  1.   2. 143.   4.   5. 143.]


In [128]:
#Filling Missing Values with a Specific Value (np.where())
# Replace NaN values with the mean of the array
mean_value = np.nanmean(data)
filled_data = np.where(np.isnan(data), mean_value, data)
print("Data After Filling NaN with Mean:", filled_data)

Data After Filling NaN with Mean: [1. 2. 3. 4. 5. 3.]


In [129]:
#Removing Missing Data (np.isnan())
# Remove NaN values from the array
cleaned_data = data[~np.isnan(data)]
print("Data After Removing NaN Values:", cleaned_data)

Data After Removing NaN Values: [1. 2. 4. 5.]


In [133]:

mean_value = np.nanstd(data)
print("Std Value:", mean_value)

mean_value = np.nanmax(data)
print("Max VAlue:", mean_value)

Std Value: 1.5811388300841898
Max VAlue: 5.0
